// <auto-generated />
namespace ElevatorSystem.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class data_seeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data_seeding));
        
        string IMigrationMetadata.Id
        {
            get { return "202206180747544_data_seeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
